/**
 * @see https://icon-sets.iconify.design/lucide/
 */
export const ui = {
  arrowUp: 'i-lucide-arrow-up',
  arrowDown: 'i-lucide-arrow-down',
  caution: 'i-lucide-circle-alert',
  copy: 'i-lucide-clipboard',
  copyCheck: 'i-lucide-check',
  dark: 'i-lucide-moon',
  error: 'i-lucide-circle-x',
  eye: 'i-lucide-eye',
  eyeOff: 'i-lucide-eye-off',
  file: 'i-lucide-file-text',
  folder: 'i-lucide-folder',
  folderOpen: 'i-lucide-folder-open',
  hash: 'i-lucide-hash',
  info: 'i-lucide-info',
  light: 'i-lucide-sun',
  menu: 'i-lucide-menu',
  panelClose: 'i-lucide-panel-left-close',
  panelOpen: 'i-lucide-panel-left-open',
  reload: 'i-lucide-rotate-ccw',
  stop: 'i-lucide-square',
  success: 'i-lucide-circle-check',
  system: 'i-lucide-monitor',
  tip: 'i-lucide-lightbulb',
  warning: 'i-lucide-triangle-alert',
  arrowLeft: 'i-lucide-arrow-left',
  arrowRight: 'i-lucide-arrow-right',
  check: 'i-lucide-check',
  chevronDoubleLeft: 'i-lucide-chevrons-left',
  chevronDoubleRight: 'i-lucide-chevrons-right',
  chevronDown: 'i-lucide-chevron-down',
  chevronLeft: 'i-lucide-chevron-left',
  chevronRight: 'i-lucide-chevron-right',
  chevronUp: 'i-lucide-chevron-up',
  close: 'i-lucide-x',
  ellipsis: 'i-lucide-ellipsis',
  external: 'i-lucide-arrow-up-right',
  loading: 'i-lucide-loader-circle',
  minus: 'i-lucide-minus',
  plus: 'i-lucide-plus',
  x: 'i-lucide-x',
  search: 'i-lucide-search',
  bookOpen: 'i-lucide-book-open-text',
  externalLink: 'i-lucide-external-link',
  timer: 'i-lucide-timer',
}

/**
 * @see https://icon-sets.iconify.design/logos/
 * @see https://icon-sets.iconify.design/vscode-icons/
 * @see https://icon-sets.iconify.design/simple-icons/
 */
export const logo = {
  // language
  js: 'i-logos-javascript',
  javascript: 'i-logos-javascript',
  jsx: 'i-logos-javascript',
  mjs: 'i-logos-javascript',
  cjs: 'i-logos-javascript',
  ts: 'i-logos-typescript-icon',
  typescript: 'i-logos-typescript-icon',
  tsx: 'i-logos-typescript-icon',
  html: 'i-logos-html-5',
  css: 'i-logos-css-3',
  json: 'i-logos-json',
  yaml: 'i-simple-icons-yaml',
  yml: 'i-simple-icons-yaml',
  md: 'i-simple-icons-markdown',
  markdown: 'i-simple-icons-markdown',
  mdc: 'i-simple-icons-markdown',
  mdx: 'i-simple-icons-mdx',
  py: 'i-logos-python',
  python: 'i-logos-python',
  ps1: 'i-vscode-icons-file-type-powershell',
  psd1: 'i-vscode-icons-file-type-powershell',
  psm1: 'i-vscode-icons-file-type-powershell',
  powershell: 'i-vscode-icons-file-type-powershell',
  terminal: 'i-lucide-terminal',
  sh: 'i-lucide-terminal',
  bash: 'i-simple-icons-gnubash',
  zsh: 'i-simple-icons-zsh',
  env: 'i-vscode-icons-file-type-dotenv',
  php: 'i-logos-php',
  java: 'i-logos-java',
  svg: 'i-logos-svg',

  // Framework, Package Manager, Library
  'tailwind css': 'i-logos-tailwindcss-icon',
  'tailwind.config.js': 'i-logos-tailwindcss-icon',
  'tailwind.config.ts': 'i-logos-tailwindcss-icon',
  vue: 'i-logos-vue',
  nuxt: 'i-logos-nuxt-icon',
  'nuxt ui': 'i-logos-nuxt-icon',
  'nuxt content': 'i-logos-nuxt-icon',
  '.nuxtrc': 'i-logos-nuxt-icon',
  '.nuxtignore': 'i-logos-nuxt-icon',
  'nuxt.config.js': 'i-logos-nuxt-icon',
  'nuxt.config.ts': 'i-logos-nuxt-icon',
  'nuxt.schema.ts': 'i-logos-nuxt-icon',
  vueuse: 'i-logos-vueuse',
  react: 'i-logos-react',
  'react.js': 'i-logos-react',
  next: 'i-logos-nextjs-icon',
  'next.js': 'i-logos-nextjs-icon',
  node: 'i-logos-nodejs-icon',
  'node.js': 'i-logos-nodejs-icon',
  'package.json': 'i-logos-nodejs-icon',
  npm: 'i-logos-npm',
  npx: 'i-logos-npm',
  '.npmrc': 'i-logos-npm',
  yarn: 'i-logos-yarn',
  'yarn.lock': 'i-logos-yarn',
  pnpm: 'i-logos-yarn',
  'pnpm-lock.yaml': 'i-logos-pnpm',
  bun: 'i-logos-bun',
  'tsconfig.json': 'i-vscode-icons-file-type-tsconfig',
  eslint: 'i-logos-eslint',
  '.eslintrc': 'i-logos-eslint',
  '.eslintrc.cjs': 'i-logos-eslint',
  '.eslintignore': 'i-logos-eslint',
  'eslint.config.js': 'i-logos-eslint',
  'eslint.config.mjs': 'i-logos-eslint',
  'eslint.config.cjs': 'i-logos-eslint',
  laravel: 'i-logos-laravel',
  spring: 'i-logos-spring-icon',
  'spring boot': 'i-logos-spring-icon',
  mermaid: 'i-vscode-icons-file-type-mermaid',

  // DB
  sql: 'i-vscode-icons-file-type-plsql',
  mysql: 'i-logos-mysql-icon',
  psql: 'i-logos-postgresql',
  pgsql: 'i-logos-postgresql',
  postgres: 'i-logos-postgresql',
  postgresql: 'i-logos-postgresql',
  sqlite: 'i-vscode-icons-file-type-sqlite',

  // Vender, OS, Application, Service, Tool, etc.
  windows: 'i-logos-microsoft-windows-icon',
  apple: 'i-simple-icons-apple',
  mac: 'i-simple-icons-apple',
  macos: 'i-simple-icons-apple',
  linux: 'i-logos-linux-tux',
  ubuntu: 'i-logos-ubuntu',
  'vs code': 'i-logos-visual-studio-code',
  '.vscode/settings.json': 'i-logos-visual-studio-code',
  git: 'i-logos-git-icon',
  '.gitignore': 'i-logos-git-icon',
  docker: 'i-logos-docker-icon',
  dockerfile: 'i-logos-docker-icon',
  editorconfig: 'i-logos-editorconfig',
  github: 'i-simple-icons-github',
  cloudflare: 'i-logos-cloudflare-icon',
  'open ai': 'i-logos-openai-icon',
  chatgpt: 'i-logos-openai-icon',
  'github copilot': 'i-logos-github-copilot',
  copilot: 'i-logos-github-copilot',
  'devcontainer.json': 'i-vscode-icons-file-type-devcontainer',
  chrome: 'i-logos-chrome',
  excel: 'i-vscode-icons-file-type-excel',

  // AWS
  aws: 'i-logos-aws',
  'aws aurora': 'i-logos-aws-aurora',
  'aws lambda': 'i-logos-aws-lambda',

  // other
  ogp: 'i-logos-open-graph',
  'open graph': 'i-logos-open-graph',
}
